---
title: "Inter-rater reliability dog goggles experiment"
author: "Lucrezia Lonardo"
format: html
editor: visual
---

```{r}
#set up
rm(list=ls())
#install.packages("irr")
library(irr)
library(tidyverse)
library(zoo)
```

```{r}
#Load data files
#first scoring (used for analyses)
first.scoring.data <- read.csv("data/scoringproject_50_Goggles_experiment.csv") %>%
  dplyr::select(Scoring:trial) %>%
  mutate(duration = Stop - Start) #%>% 
  #mutate(Behaviour = str_replace_all(Behaviour, " ", ""))

levels(as.factor(first.scoring.data$Subject))


first.scoring.data.red<-first.scoring.data %>% 
filter(Subject %in% c("Daytona", 	"Keres",	"Cully",	"Leia",	"Jasper",	"Stella4",	"Thaya",	 "Riu", "Ronja7", "Tenya", "Samira")) #only keep dogs coded by second scorer too


#manipulation check
#Cully did not pass the manipulation check so scorer 1 did not score his manipulation check phase For this reason he is excluded from the calculation of the agreement on the manipulation check
man.check.data<-first.scoring.data.red %>% 
filter(Behaviour=="Manipulation check ")

man.check.data<-man.check.data[!duplicated(man.check.data$Subject),] #only keep first row per subject (i.e., first screen approached)

#first looks
first.looks.data1<-first.scoring.data.red %>% 
filter(Behaviour=="First look")
#LL: I can use the dataframe "first.looks.data" for calculating agreement on first looks. 
#use first.looks.data1$Value

#Aggregated data 1st scoring
agg.data1<-first.scoring.data.red %>%
  droplevels()%>%
  filter(!is.na(trial)) %>% #remove manipulation check
  filter(Behaviour!="Trial ") %>% 
  group_by(Subject, trial, Behaviour, Value)%>%
  summarise(sum_duration=sum(duration))%>%
  ungroup()%>%
  droplevels()%>%
  complete(Subject, trial, Value, fill=list(sum.duration=0)) #fill in 0s
  

#Looking duration transparent 1
agg.data.dur.transp1<-agg.data1 %>% 
  filter(Value=="Duration looking transparent") 
#Looking duration opaque 1
agg.data.dur.opaque1<-agg.data1 %>% 
  filter(Value=="Duration looking opaque") 
#First choice 1
agg.data.first.choice1<-agg.data1 %>% 
  filter(Behaviour=="First target choice") %>%  
  select(Subject:Behaviour)
#Riu trial 3 no choice

#Inspection behind screen 1
agg.data.inspection1<-agg.data1 %>% 
  filter(Behaviour=="Inspection behind screen") %>%  
  select(Subject:Behaviour) %>% 
  complete(Subject, trial, Behaviour, fill=list(Value=NA))
```

```{r}
#second scoring (30% of subjects)
second.scoring.data<- read.csv("data/inter-rater_reliability/scoringproject_101_Goggles_reliability.csv") %>% 
  dplyr::select(Scoring:Value) %>%
  mutate(duration = Stop - Start) 

#manipulation check
man.check.data2<-second.scoring.data%>% 
filter(Behaviour=="Manipulation check")

man.check.data2<-man.check.data2[!duplicated(man.check.data2$Subject),] #only keep first row per subject (i.e., first screen approached)
#exclude Cully
man.check.data2<-man.check.data2 %>% 
  filter(Subject!="Cully")


#Aggregated data 2nd scoring
agg.data2<-second.scoring.data %>%
  droplevels()%>%
  filter(Behaviour!="Manipulation check") %>% #remove manipulation check
  mutate(trial=ifelse(Behaviour=="Trial", Value, NA)) %>% 
  mutate(trial=na.locf(trial)) %>% 
  filter(Behaviour!="Trial") %>% 
  group_by(Subject, trial, Behaviour, Value)%>%
  summarise(sum_duration=sum(duration))%>%
  ungroup()%>%
  droplevels()%>%
  complete(Subject, trial, Value, fill=list(sum.duration=0)) #fill in 0s

#First looks 2nd coder
first.looks.data2<-agg.data2 %>% 
filter(Behaviour=="First look") %>% 
  select(-"sum_duration")


#Looking duration transparent 2
agg.data.dur.transp2<-agg.data2 %>% 
  filter(Value=="Duration looking transparent") 
#Looking duration opaque 2
agg.data.dur.opaque2<-agg.data2 %>% 
  filter(Value=="Duration looking opaque") 
#First choice 2
agg.data.first.choice2<-agg.data2 %>% 
  filter(Behaviour=="First target choice") %>%  
  select(Subject:Behaviour)
#Riu trial 3 no choice

#Inspection behind screen 2nd coder
agg.data.inspection2<-agg.data2 %>% 
  filter(Behaviour=="Inspection behind screen") %>%  
  select(Subject:Behaviour)

agg.data.inspection2<-agg.data.inspection2[!duplicated(agg.data.inspection2[1:2]),] %>% #only keep unique values per subject and trial (i.e., first tunnel inspected)
complete(Subject, trial, Behaviour, fill=list(Value=NA))
```

```{r}
##create dataframes

#manipulation check
man.check.datafr<-data.frame(man.check.data$Subject,man.check.data$Value, man.check.data2$Subject, man.check.data2$Value)
#reorder so that subjects match  
man.check.datafr.rearranged1<-man.check.datafr[order(man.check.datafr$man.check.data.Subject),1:2]
man.check.datafr.rearranged2<-man.check.datafr[order(man.check.datafr$man.check.data2.Subject),3:4]
man.check.datafr.rearranged<-cbind(man.check.datafr.rearranged1, man.check.datafr.rearranged2)

#first looks
first.looks.datafr<-data.frame(first.looks.data1$Subject, first.looks.data1$Value,  first.looks.data2$Subject, first.looks.data2$Value)
#reorder so that subjects match  
first.looks.datafr.rearranged1<-first.looks.datafr[order(first.looks.datafr$first.looks.data1.Subject),1:2]
first.looks.datafr.rearranged2<-first.looks.datafr[order(first.looks.datafr$first.looks.data2.Subject),3:4]
first.looks.datafr.rearranged<-cbind(first.looks.datafr.rearranged1, first.looks.datafr.rearranged2)

#duration looking 
dur.looking<-data.frame(agg.data.dur.transp1$Subject, agg.data.dur.transp1$sum_duration, agg.data.dur.transp2$sum_duration, agg.data.dur.opaque1$Subject, agg.data.dur.opaque1$sum_duration, agg.data.dur.opaque2$sum_duration)

#first choice
first.choices<-data.frame(agg.data.first.choice1, agg.data.first.choice2$Value)

#inspection behind screens
inspections.datafr<-data.frame(agg.data.inspection1[,c("Subject", "trial", "Value")], agg.data.inspection2[,c("Subject", "Value")]) %>% 
  rename(Value.2=Value.1)
```


```{r}
#Agreement on duration looking transparent: continuous variable, two-way random effects model, single rater, consistency (not interested in absolute values)
#ICC=Interclass correlation coefficient

icc(
  dur.looking[,c(2:3)], model = "twoway", 
  type = "consistency", unit = "single"
  )

#Agreement on duration looking opaque: continuous variable, two-way random effects model, single rater, consistency (not interested in absolute values)
#ICC=Interclass correlation coefficient

icc(
  dur.looking[,c(5:6)], model = "twoway", 
  type = "consistency", unit = "single"
  )

#But this assumes every obs is a subject

shapiro.test(dur.looking[,2])
shapiro.test(dur.looking[,3]) #neither is normally distributed

#Spearman transparent
cor.test(dur.looking[,2], dur.looking[,3], method= "spearman", use="complete.obs")
length(dur.looking[,2])

#Spearman opaque
cor.test(dur.looking[,5], dur.looking[,6], method= "spearman", use="complete.obs")
length(dur.looking[,5])
```

```{r}
#Agreement on first choice
#Cohen's Kappa
kappa2(first.choices[,c(3,5)])
```

```{r}
#Agreement on manipulation check
#Cohen's Kappa
kappa2(man.check.datafr.rearranged[,c(2,4)])
```
```{r}
#Agreement on first look
kappa2(first.looks.datafr.rearranged[,c(2,4)])
```
```{r}
#Agreement on inspections behind screens
kappa2(inspections.datafr[,c(3,5)])
```

